[2023-07-20T20:11:14.217+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-20T20:10:25.972445+00:00 [queued]>
[2023-07-20T20:11:14.251+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-20T20:10:25.972445+00:00 [queued]>
[2023-07-20T20:11:14.251+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-20T20:11:14.252+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-20T20:11:14.252+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-20T20:11:14.289+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-20 20:10:25.972445+00:00
[2023-07-20T20:11:14.304+0000] {standard_task_runner.py:55} INFO - Started process 607504 to run task
[2023-07-20T20:11:14.320+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'manual__2023-07-20T20:10:25.972445+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmp0dv0txdc']
[2023-07-20T20:11:14.322+0000] {standard_task_runner.py:83} INFO - Job 164: Subtask load_task
[2023-07-20T20:11:14.599+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-20T20:10:25.972445+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-20T20:11:14.821+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-20T20:10:25.972445+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-20T20:10:25.972445+00:00
[2023-07-20T20:11:14.841+0000] {logging_mixin.py:137} INFO - Error connecting to the database: connection to server at "real-estate-db.czvpezojzuuw.ap-southeast-2.rds.amazonaws.com" (172.31.48.42), port 5432 failed: fe_sendauth: no password supplied
[2023-07-20T20:11:14.842+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 107, in load_to_rds
    cursor = conn.cursor()
UnboundLocalError: local variable 'conn' referenced before assignment
[2023-07-20T20:11:14.899+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230720T201025, start_date=20230720T201114, end_date=20230720T201114
[2023-07-20T20:11:14.935+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 164 for task load_task (local variable 'conn' referenced before assignment; 607504)
[2023-07-20T20:11:14.967+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-20T20:11:15.137+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
