[2023-07-11T14:54:09.971+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T14:53:22.587917+00:00 [queued]>
[2023-07-11T14:54:10.000+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T14:53:22.587917+00:00 [queued]>
[2023-07-11T14:54:10.000+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T14:54:10.000+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-11T14:54:10.003+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T14:54:10.038+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-11 14:53:22.587917+00:00
[2023-07-11T14:54:10.053+0000] {standard_task_runner.py:55} INFO - Started process 45875 to run task
[2023-07-11T14:54:10.072+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'manual__2023-07-11T14:53:22.587917+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpgg70ms1i']
[2023-07-11T14:54:10.075+0000] {standard_task_runner.py:83} INFO - Job 103: Subtask load_task
[2023-07-11T14:54:10.304+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T14:53:22.587917+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T14:54:10.540+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-11T14:53:22.587917+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-11T14:53:22.587917+00:00
[2023-07-11T14:54:10.588+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-11T14:54:10.602+0000] {logging_mixin.py:137} INFO - Table created successfully!
[2023-07-11T14:54:10.725+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 130, in load_to_rds
    data = [(row[0], row[1], row[2], row[3], row[4], row[5], row[6]) for row in all_listing_info]
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 130, in <listcomp>
    data = [(row[0], row[1], row[2], row[3], row[4], row[5], row[6]) for row in all_listing_info]
KeyError: 0
[2023-07-11T14:54:10.770+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230711T145322, start_date=20230711T145409, end_date=20230711T145410
[2023-07-11T14:54:10.791+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 103 for task load_task (0; 45875)
[2023-07-11T14:54:10.841+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T14:54:10.929+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
