[2023-07-10T04:34:20.947+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_daily_dag.connect_to_rds manual__2023-07-09T16:55:01.341157+00:00 [queued]>
[2023-07-10T04:34:21.047+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_daily_dag.connect_to_rds manual__2023-07-09T16:55:01.341157+00:00 [queued]>
[2023-07-10T04:34:21.047+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-10T04:34:21.048+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-07-10T04:34:21.048+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-10T04:34:21.174+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): connect_to_rds> on 2023-07-09 16:55:01.341157+00:00
[2023-07-10T04:34:21.201+0000] {standard_task_runner.py:55} INFO - Started process 1409 to run task
[2023-07-10T04:34:21.214+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_daily_dag', 'connect_to_rds', 'manual__2023-07-09T16:55:01.341157+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpq1s8oo0q']
[2023-07-10T04:34:21.217+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask connect_to_rds
[2023-07-10T04:34:22.145+0000] {task_command.py:389} INFO - Running <TaskInstance: my_daily_dag.connect_to_rds manual__2023-07-09T16:55:01.341157+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-10T04:34:22.907+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_daily_dag
AIRFLOW_CTX_TASK_ID=connect_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-07-09T16:55:01.341157+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-09T16:55:01.341157+00:00
[2023-07-10T04:34:23.078+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-10T04:34:23.227+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/first_dag.py", line 43, in connect_to_rds
    context['ti'].xcom_push(key='conn', value=conn)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2294, in xcom_push
    XCom.set(
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'psycopg2.extensions.connection' object has no attribute '__module__'. Did you mean: '__reduce__'?
[2023-07-10T04:34:23.455+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=my_daily_dag, task_id=connect_to_rds, execution_date=20230709T165501, start_date=20230710T043420, end_date=20230710T043423
[2023-07-10T04:34:23.554+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 46 for task connect_to_rds ('psycopg2.extensions.connection' object has no attribute '__module__'; 1409)
[2023-07-10T04:34:23.649+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-10T04:34:23.963+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
