[2023-07-09T17:05:58.604+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_daily_dag.connect_to_rds manual__2023-07-09T16:55:01.341157+00:00 [queued]>
[2023-07-09T17:05:58.671+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_daily_dag.connect_to_rds manual__2023-07-09T16:55:01.341157+00:00 [queued]>
[2023-07-09T17:05:58.672+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-09T17:05:58.672+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-07-09T17:05:58.672+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-09T17:05:58.788+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): connect_to_rds> on 2023-07-09 16:55:01.341157+00:00
[2023-07-09T17:05:58.815+0000] {standard_task_runner.py:55} INFO - Started process 11043 to run task
[2023-07-09T17:05:58.849+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_daily_dag', 'connect_to_rds', 'manual__2023-07-09T16:55:01.341157+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpa8316u6v']
[2023-07-09T17:05:58.883+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask connect_to_rds
[2023-07-09T17:05:59.966+0000] {task_command.py:389} INFO - Running <TaskInstance: my_daily_dag.connect_to_rds manual__2023-07-09T16:55:01.341157+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-09T17:06:00.703+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_daily_dag
AIRFLOW_CTX_TASK_ID=connect_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-07-09T16:55:01.341157+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-09T16:55:01.341157+00:00
[2023-07-09T17:06:00.800+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-09T17:06:00.801+0000] {python.py:177} INFO - Done. Returned value was: <connection object at 0x7f037d16ce00; dsn: 'user=postgres password=xxx dbname='' host=real-estate-db.czvpezojzuuw.ap-southeast-2.rds.amazonaws.com port=5432', closed: 0>
[2023-07-09T17:06:00.981+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2294, in xcom_push
    XCom.set(
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'psycopg2.extensions.connection' object has no attribute '__module__'. Did you mean: '__reduce__'?
[2023-07-09T17:06:01.146+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=my_daily_dag, task_id=connect_to_rds, execution_date=20230709T165501, start_date=20230709T170558, end_date=20230709T170601
[2023-07-09T17:06:01.209+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 33 for task connect_to_rds ('psycopg2.extensions.connection' object has no attribute '__module__'; 11043)
[2023-07-09T17:06:01.250+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-09T17:06:01.557+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
