[2023-07-09T15:46:31.817+0000] {processor.py:153} INFO - Started process (PID=1239) to work on /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:46:31.818+0000] {processor.py:743} INFO - Processing file /home/ubuntu/airflow/dags/connect.py for tasks to queue
[2023-07-09T15:46:31.819+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:46:31.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:46:31.831+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:46:31.821+0000] {dagbag.py:343} ERROR - Failed to import: /home/ubuntu/airflow/dags/connect.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/connect.py", line 42
    	conn.commit()
    ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-07-09T15:46:31.831+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:46:31.933+0000] {processor.py:175} INFO - Processing /home/ubuntu/airflow/dags/connect.py took 0.121 seconds
[2023-07-09T15:47:02.056+0000] {processor.py:153} INFO - Started process (PID=1491) to work on /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:47:02.058+0000] {processor.py:743} INFO - Processing file /home/ubuntu/airflow/dags/connect.py for tasks to queue
[2023-07-09T15:47:02.059+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:47:02.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:47:02.067+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:47:02.062+0000] {dagbag.py:343} ERROR - Failed to import: /home/ubuntu/airflow/dags/connect.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/connect.py", line 42
    	conn.commit()
    ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-07-09T15:47:02.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:47:02.161+0000] {processor.py:175} INFO - Processing /home/ubuntu/airflow/dags/connect.py took 0.114 seconds
[2023-07-09T15:47:32.475+0000] {processor.py:153} INFO - Started process (PID=1730) to work on /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:47:32.476+0000] {processor.py:743} INFO - Processing file /home/ubuntu/airflow/dags/connect.py for tasks to queue
[2023-07-09T15:47:32.476+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:47:32.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:47:32.479+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:47:32.478+0000] {dagbag.py:343} ERROR - Failed to import: /home/ubuntu/airflow/dags/connect.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/connect.py", line 42
    	conn.commit()
    ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-07-09T15:47:32.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:47:32.512+0000] {processor.py:175} INFO - Processing /home/ubuntu/airflow/dags/connect.py took 0.040 seconds
[2023-07-09T15:49:51.227+0000] {processor.py:153} INFO - Started process (PID=2072) to work on /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:49:51.237+0000] {processor.py:743} INFO - Processing file /home/ubuntu/airflow/dags/connect.py for tasks to queue
[2023-07-09T15:49:51.238+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:49:51.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:49:51.242+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:49:51.240+0000] {dagbag.py:343} ERROR - Failed to import: /home/ubuntu/airflow/dags/connect.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/connect.py", line 42
    	conn.commit()
    ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-07-09T15:49:51.243+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:49:51.303+0000] {processor.py:175} INFO - Processing /home/ubuntu/airflow/dags/connect.py took 0.081 seconds
[2023-07-09T15:50:22.242+0000] {processor.py:153} INFO - Started process (PID=2309) to work on /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:50:22.243+0000] {processor.py:743} INFO - Processing file /home/ubuntu/airflow/dags/connect.py for tasks to queue
[2023-07-09T15:50:22.244+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:50:22.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:50:22.248+0000] {logging_mixin.py:137} INFO - [2023-07-09T15:50:22.247+0000] {dagbag.py:343} ERROR - Failed to import: /home/ubuntu/airflow/dags/connect.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/connect.py", line 42
    	conn.commit()
    ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-07-09T15:50:22.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/connect.py
[2023-07-09T15:50:22.326+0000] {processor.py:175} INFO - Processing /home/ubuntu/airflow/dags/connect.py took 0.091 seconds
