[2023-07-11T15:21:44.846+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T15:15:39.857065+00:00 [queued]>
[2023-07-11T15:21:44.860+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T15:15:39.857065+00:00 [queued]>
[2023-07-11T15:21:44.860+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T15:21:44.860+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 4
[2023-07-11T15:21:44.860+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T15:21:44.892+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-11 15:15:39.857065+00:00
[2023-07-11T15:21:44.906+0000] {standard_task_runner.py:55} INFO - Started process 57830 to run task
[2023-07-11T15:21:44.922+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'manual__2023-07-11T15:15:39.857065+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmp9p6lf5a4']
[2023-07-11T15:21:44.929+0000] {standard_task_runner.py:83} INFO - Job 131: Subtask load_task
[2023-07-11T15:21:45.229+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T15:15:39.857065+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T15:21:45.543+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-11T15:15:39.857065+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-11T15:15:39.857065+00:00
[2023-07-11T15:21:45.631+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-11T15:21:46.409+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 125, in load_to_rds
    cursor.execute(create_table_query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(listings_id_seq, 2200) already exists.

[2023-07-11T15:21:46.457+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230711T151539, start_date=20230711T152144, end_date=20230711T152146
[2023-07-11T15:21:46.493+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 131 for task load_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(listings_id_seq, 2200) already exists.
; 57830)
[2023-07-11T15:21:46.534+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T15:21:46.650+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
