[2023-07-11T14:39:57.186+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-11T14:39:15.499849+00:00 [queued]>
[2023-07-11T14:39:57.197+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-11T14:39:15.499849+00:00 [queued]>
[2023-07-11T14:39:57.197+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T14:39:57.197+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-11T14:39:57.197+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T14:39:57.209+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_task> on 2023-07-11 14:39:15.499849+00:00
[2023-07-11T14:39:57.217+0000] {standard_task_runner.py:55} INFO - Started process 38912 to run task
[2023-07-11T14:39:57.221+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'transform_task', 'manual__2023-07-11T14:39:15.499849+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmp3c9z6d43']
[2023-07-11T14:39:57.224+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask transform_task
[2023-07-11T14:39:57.354+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-11T14:39:15.499849+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T14:39:57.486+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-11T14:39:15.499849+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-11T14:39:15.499849+00:00
[2023-07-11T14:39:57.519+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 72, in clean_data
    head(df)
NameError: name 'head' is not defined
[2023-07-11T14:39:57.541+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=transform_task, execution_date=20230711T143915, start_date=20230711T143957, end_date=20230711T143957
[2023-07-11T14:39:57.553+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 79 for task transform_task (name 'head' is not defined; 38912)
[2023-07-11T14:39:57.594+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T14:39:57.641+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
