[2023-07-20T20:16:24.879+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task scheduled__2023-07-19T20:05:06.697330+00:00 [queued]>
[2023-07-20T20:16:24.887+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task scheduled__2023-07-19T20:05:06.697330+00:00 [queued]>
[2023-07-20T20:16:24.887+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-20T20:16:24.888+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-07-20T20:16:24.888+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-20T20:16:24.899+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-19 20:05:06.697330+00:00
[2023-07-20T20:16:24.905+0000] {standard_task_runner.py:55} INFO - Started process 610889 to run task
[2023-07-20T20:16:24.909+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'scheduled__2023-07-19T20:05:06.697330+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpdwz74fz3']
[2023-07-20T20:16:24.911+0000] {standard_task_runner.py:83} INFO - Job 167: Subtask load_task
[2023-07-20T20:16:25.057+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task scheduled__2023-07-19T20:05:06.697330+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-20T20:16:25.189+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-19T20:05:06.697330+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-19T20:05:06.697330+00:00
[2023-07-20T20:16:25.206+0000] {logging_mixin.py:137} INFO - Error connecting to the database: connection to server at "real-estate-db.czvpezojzuuw.ap-southeast-2.rds.amazonaws.com" (172.31.48.42), port 5432 failed: fe_sendauth: no password supplied
[2023-07-20T20:16:25.206+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 107, in load_to_rds
    cursor = conn.cursor()
UnboundLocalError: local variable 'conn' referenced before assignment
[2023-07-20T20:16:25.229+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230719T200506, start_date=20230720T201624, end_date=20230720T201625
[2023-07-20T20:16:25.241+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 167 for task load_task (local variable 'conn' referenced before assignment; 610889)
[2023-07-20T20:16:25.282+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-20T20:16:25.314+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
