[2023-07-18T07:52:20.522+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task scheduled__2023-07-17T07:50:10.529377+00:00 [queued]>
[2023-07-18T07:52:20.543+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task scheduled__2023-07-17T07:50:10.529377+00:00 [queued]>
[2023-07-18T07:52:20.543+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-18T07:52:20.543+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-18T07:52:20.543+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-18T07:52:20.573+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-17 07:50:10.529377+00:00
[2023-07-18T07:52:20.587+0000] {standard_task_runner.py:55} INFO - Started process 25238 to run task
[2023-07-18T07:52:20.597+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'scheduled__2023-07-17T07:50:10.529377+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpe7q94de2']
[2023-07-18T07:52:20.604+0000] {standard_task_runner.py:83} INFO - Job 156: Subtask load_task
[2023-07-18T07:52:20.919+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task scheduled__2023-07-17T07:50:10.529377+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-18T07:52:21.170+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-17T07:50:10.529377+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-17T07:50:10.529377+00:00
[2023-07-18T07:52:21.241+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-18T07:52:22.071+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 123, in load_to_rds
    cursor.execute(create_table_query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(listings_id_seq, 2200) already exists.

[2023-07-18T07:52:22.155+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230717T075010, start_date=20230718T075220, end_date=20230718T075222
[2023-07-18T07:52:22.201+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 156 for task load_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(listings_id_seq, 2200) already exists.
; 25238)
[2023-07-18T07:52:22.260+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-18T07:52:22.423+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
